# Generated by Django 3.2.9 on 2022-02-18 20:44

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('LoginScreen', '0003_gpsdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='GPSData',
        ),
        migrations.RemoveField(
            model_name='category',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='category',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='category',
            name='uniqueId',
        ),
        migrations.RemoveField(
            model_name='image',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='image',
            name='hashtags',
        ),
        migrations.RemoveField(
            model_name='image',
            name='landImage',
        ),
        migrations.RemoveField(
            model_name='image',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='image',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='image',
            name='tallImage',
        ),
        migrations.RemoveField(
            model_name='image',
            name='uniqueId',
        ),
        migrations.AlterField(
            model_name='image',
            name='squareImage',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_square.jpg', force_format=None, keep_meta=True, quality=0, size=[1000, 1000], upload_to='DB Pictures'),
        ),
    ]
