# Generated by Django 3.2.9 on 2022-04-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginScreen', '0006_auto_20220221_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedata',
            name='fileupload',
            field=models.FileField(default=1, upload_to='media\\CSV Files'),
            preserve_default=False,
        ),
    ]
